# Generated by Django 2.2.10 on 2020-09-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskfb', '0004_auto_20200924_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('text', 'ответ текстом'), ('multi_choice', 'ответ с выбором нескольких вариантов'), ('choice', 'ответ с выбором одного варианта')], max_length=255),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('text', models.TextField(blank=True)),
                ('answer', models.ManyToManyField(null=True, related_name='user_answers', to='taskfb.Answer')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
            },
        ),
    ]
