# Generated by Django 2.2.10 on 2020-09-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskfb', '0005_auto_20200924_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='taskfb.Question'),
            preserve_default=False,
        ),
    ]
