# Generated by Django 2.2.10 on 2020-09-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskfb', '0006_useranswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user_id',
        ),
    ]
