# Generated by Django 2.2.10 on 2020-09-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskfb', '0008_auto_20200924_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='user_answers', to='taskfb.Answer'),
        ),
    ]
