# Generated by Django 2.2.10 on 2020-09-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskfb', '0009_auto_20200924_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='answer', to='taskfb.Answer'),
        ),
    ]
